import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:webview_flutter/webview_flutter.dart';
import '../../data/wallet_repository.dart';

/// Result returned when the WebView screen pops.
enum KashierPaymentResult { success, failure, cancelled }

/// In-app WebView for Kashier hosted checkout.
///
/// Monitors navigation URLs to detect Kashier's success/failure redirects
/// without relying on a Webhook. After detecting success, it credits the
/// wallet in Supabase via [WalletRepository.confirmKashierPayment].
///
/// Production-ready design:
///   • Guards against double-crediting (repository checks for existing
///     completed transaction before writing).
///   • When a Webhook is later enabled, this client-side call becomes a
///     transparent no-op (credit already applied by Webhook).
///   • The [orderId] and [amount] are passed from the caller — never
///     extracted from the URL — to prevent tampering.
class KashierWebViewScreen extends ConsumerStatefulWidget {
  const KashierWebViewScreen({
    super.key,
    required this.paymentUrl,
    required this.orderId,
    required this.amount,
  });

  /// Signed Kashier checkout URL from the Edge Function.
  final String paymentUrl;

  /// The merchant order ID generated by the Edge Function (e.g. TR-xxxxx-timestamp).
  /// Used to match the transaction in Supabase — never parsed from the redirect URL.
  final String orderId;

  /// Amount in EGP that will be credited on success.
  final double amount;

  @override
  ConsumerState<KashierWebViewScreen> createState() =>
      _KashierWebViewScreenState();
}

class _KashierWebViewScreenState extends ConsumerState<KashierWebViewScreen> {
  late final WebViewController _controller;

  /// Prevents processing the same success/failure URL more than once.
  bool _resultHandled = false;

  /// Tracks page loading to show/hide the progress indicator.
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _initWebView();
  }

  void _initWebView() {
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onPageStarted: (_) => _setLoading(true),
          onPageFinished: (url) {
            _setLoading(false);
            _handleUrl(url);
          },
          onNavigationRequest: (request) {
            _handleUrl(request.url);
            // Always allow navigation inside the WebView
            return NavigationDecision.navigate;
          },
          onWebResourceError: (error) {
            // Only report errors that aren't caused by Kashier's own redirects
            if (!_resultHandled) {
              debugPrint(
                '[KashierWebView] Resource error: ${error.description}',
              );
            }
          },
        ),
      )
      ..loadRequest(Uri.parse(widget.paymentUrl));
  }

  void _setLoading(bool value) {
    if (mounted) setState(() => _isLoading = value);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // URL Inspection
  // Kashier appends `paymentStatus=SUCCESS|FAILURE` and `merchantOrderId`
  // to the redirect URL after checkout completion.
  // ─────────────────────────────────────────────────────────────────────────
  void _handleUrl(String url) {
    if (_resultHandled) return;
    final uri = Uri.tryParse(url);
    if (uri == null) return;

    final params = uri.queryParameters;
    final status = (params['paymentStatus'] ?? '').toUpperCase();

    if (status == 'SUCCESS') {
      _resultHandled = true;
      _onPaymentSuccess();
    } else if (status == 'FAILURE' || status == 'FAILED') {
      _resultHandled = true;
      _onPaymentFailure();
    }
    // Still-loading pages / intermediate URLs are ignored
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Success Handler
  // ─────────────────────────────────────────────────────────────────────────
  Future<void> _onPaymentSuccess() async {
    _setLoading(true); // Show loading while updating Supabase
    try {
      final repo = ref.read(walletRepositoryProvider);
      await repo.confirmKashierPayment(
        orderId: widget.orderId,
        amount: widget.amount,
      );
      if (mounted) {
        Navigator.of(context).pop(KashierPaymentResult.success);
      }
    } catch (e) {
      // If the Supabase update fails, still inform the user to check their
      // balance — the Webhook may have already applied the credit.
      if (mounted) {
        _setLoading(false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              'تم الدفع بنجاح، لكن حدث خطأ في تحديث رصيدك تلقائياً.\n'
              'يرجى التحقق من رصيدك خلال دقائق أو التواصل مع الدعم.',
              style: const TextStyle(fontSize: 13),
            ),
            backgroundColor: Colors.orange.shade700,
            duration: const Duration(seconds: 6),
          ),
        );
        // Pop with success anyway — payment was confirmed by Kashier
        await Future.delayed(const Duration(seconds: 2));
        if (mounted) Navigator.of(context).pop(KashierPaymentResult.success);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Failure Handler
  // ─────────────────────────────────────────────────────────────────────────
  void _onPaymentFailure() {
    if (mounted) Navigator.of(context).pop(KashierPaymentResult.failure);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Back Button Confirmation
  // ─────────────────────────────────────────────────────────────────────────
  Future<bool> _onWillPop() async {
    if (_resultHandled) return true;
    final confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('إلغاء الدفع؟'),
        content: const Text(
          'لم تُكتمل عملية الدفع بعد. هل تريد الخروج؟',
          textAlign: TextAlign.right,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('لا، أكمل الدفع'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
            child: const Text(
              'نعم، إلغاء',
              style: TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
    return confirm ?? false;
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, _) async {
        if (didPop) return;
        final shouldPop = await _onWillPop();
        if (shouldPop && context.mounted) {
          Navigator.of(context).pop(KashierPaymentResult.cancelled);
        }
      },
      child: Scaffold(
        appBar: AppBar(
          title: const Text('بوابة الدفع – Kashier'),
          backgroundColor: const Color(0xFF1a3c6e),
          foregroundColor: Colors.white,
          centerTitle: true,
          leading: IconButton(
            icon: const Icon(Icons.close),
            tooltip: 'إغلاق',
            onPressed: () async {
              final shouldPop = await _onWillPop();
              if (shouldPop && context.mounted) {
                Navigator.of(context).pop(KashierPaymentResult.cancelled);
              }
            },
          ),
          // Security badge — reassures the user the page is legitimate
          actions: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 12),
              child: Row(
                children: [
                  Icon(Icons.lock, size: 16, color: Colors.green.shade300),
                  const SizedBox(width: 4),
                  Text(
                    'آمن',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.green.shade300,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        body: Stack(
          children: [
            WebViewWidget(controller: _controller),
            if (_isLoading)
              const Positioned(
                top: 0,
                left: 0,
                right: 0,
                child: LinearProgressIndicator(
                  backgroundColor: Colors.transparent,
                  valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF1a3c6e)),
                ),
              ),
          ],
        ),
      ),
    );
  }
}
